### ISSUE TITLE
[Performance] Resize image to a smaller size for faster processing

### ISSUE THREAD

**Issue by tomrod10** [tomrod10/cpm#10]
#### Description
After using the working and fully implemented parts of CPM (random color selection on image) it's apparent that generating random `x` and `y` coordinates and getting the pixel data takes a noticeable amount of time 500 to 1000ms. 

To continue to allow the users to select whichever image they like to use without worrying about the size of it and to provide an enjoyable user experience, resizing the image to a smaller size is a good first step to achieve a quick and responsive feel.

#### Screenshots
None

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.
- `/cpm_app/utils.py`
- `/cpm_app/tests/test_ResizeImage`

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.
N/A

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Write logic to resize image selected to a smaller size
- [ ] Write a small script to compare performance improvement
- [ ] Write tests to verify resizing works as expected
