### ISSUE TITLE
[Core] Write logic to generate an analogous color palette

### ISSUE THREAD

**Issue by tomrod10** [tomrod10/cpm#14]
#### Description
Write logic to generate an analogous color palette based on the color selected from image. 

This will potentially call for refactoring on how I wrote the function calls to generate color palettes for different color schemes. Do we, 
- Create functions for each color scheme and add conditionals in the flow to call a function depending on user input?
OR 
- Create a function where we pass the color, format and scheme and it returns the color palette? 

#### Screenshots
None

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.
- `/cpm_app/utils.py`
- `/cpm_app/cli_flow/flow.py`

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.
N/A

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Pass in selected color from image and process colors in a sound manner to generate an analogous color palette
- [x] Algorithm should generate a 5-step/color monochromatic color palette
- [ ] Implement test suite
