### ISSUE TITLE
[Core] Write logic to generate monochromatic color palette based on uploaded image

### ISSUE THREAD

**Issue by tomrod10** [tomrod10/cpm#7]
#### Description
Write logic to generate a monochromatic color palette based on the color selected from image.

#### Screenshots
None

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.
- `/cpm_app/utils.py`
- `/cpm_app/cli_flow/flow.py`

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.
N/A

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Pass in selected color from image and process colors in a sound manner to generate a monochromatic color palette
- [x] Algorithm should generate a 5-step/color monochromatic color palette
- [x] Implement test suite
