### ISSUE TITLE
[Core] Write logic to extract color from image 

### ISSUE THREAD

**Issue by tomrod10** [tomrod10/cpm#8]
#### Description
For this first iteration we'll focus on creating a helper function that selects a random spot within the image area and extract the color data. The color data will be converted to HSL if necessary and returned.

In later tickets I'll focus on creating functions to generate color palettes for different color schemes. 

#### Screenshots
None

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.
- `/cpm_app/utils.py`
- `/cpm_app/tests/test_GetColorFromImage`

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.
N/A

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Write function to extract color at random point within image area
- [x] Convert color extracted to HLS format
- [x] Implement test suite for function
